/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/components/auth/AuthForm.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    BreadCrumbs: typeof import('./src/components/common/navigate/BreadCrumbs.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Editor: typeof import('./src/components/Tiptap/Editor.vue')['default']
    EditorRrrrrrrrrrrrrrr2: typeof import('./src/components/Tiptap/Editor-rrrrrrrrrrrrrrr2.vue')['default']
    Index: typeof import('./src/components/Article/Create/Index.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LeftSideBar: typeof import('./src/components/layouts/appLayout/LeftSideBar.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    ModalSpiner: typeof import('./src/components/common/spiner/ModalSpiner.vue')['default']
    PageSpiner: typeof import('./src/components/common/spiner/PageSpiner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Test: typeof import('./src/components/Catalog/Create/Test.vue')['default']
    Tiptapr3r3r3r3r3r: typeof import('./src/components/Tiptap/Tiptapr3r3r3r3r3r.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TopPanel: typeof import('./src/components/layouts/appLayout/TopPanel.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
