name: Laravel Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: app_test
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: pgsql, mbstring, xml, curl, dom, fileinfo, intl, json, zip

    - name: Install dependencies
      working-directory: ./backend
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Create .env.testing
      working-directory: ./backend
      run: |
        cp .env.dev.example .env.testing
        echo "APP_ENV=testing" >> .env.testing
        echo "APP_DEBUG=true" >> .env.testing
        echo "APP_KEY=base64:$(openssl rand -base64 32)" >> .env.testing
        echo "DB_CONNECTION=pgsql" >> .env.testing
        echo "DB_HOST=localhost" >> .env.testing
        echo "DB_PORT=5432" >> .env.testing
        echo "DB_DATABASE=app_test" >> .env.testing
        echo "DB_USERNAME=laravel" >> .env.testing
        echo "DB_PASSWORD=secret" >> .env.testing
        echo "CACHE_DRIVER=array" >> .env.testing
        echo "SESSION_DRIVER=array" >> .env.testing
        echo "QUEUE_CONNECTION=sync" >> .env.testing
        echo "MAIL_MAILER=array" >> .env.testing

    - name: Copy .env.testing to .env
      working-directory: ./backend
      run: cp .env.testing .env

    - name: Generate application key
      working-directory: ./backend
      run: php artisan key:generate

    - name: Wait for PostgreSQL to be ready
      run: |
        echo "Waiting for PostgreSQL..."
        for i in {1..30}; do
          if nc -z localhost 5432; then
            echo "PostgreSQL is ready!"
            break
          fi
          echo "Waiting for PostgreSQL... attempt $i"
          sleep 2
        done

    - name: Run database migrations
      working-directory: ./backend
      run: php artisan migrate --env=testing --force

    - name: Run tests
      working-directory: ./backend
      run: ./vendor/bin/phpunit