name: Laravel Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: app_test
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: pgsql, mbstring, xml, curl, dom, fileinfo, intl, json, zip

    - name: Setup environment
      working-directory: ./backend
      run: |
        cp .env.testing .env
        php artisan key:generate

    - name: Install dependencies
      working-directory: ./backend
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Wait for PostgreSQL
      working-directory: ./backend
      run: sleep 10

    - name: Run tests
      working-directory: ./backend
      run: ./vendor/bin/phpunit