name: Laravel Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: app_test
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: pgsql, mbstring, xml, curl, dom, fileinfo, intl, json, zip

    - name: Setup environment
      working-directory: ./backend
      run: |
        cp .env.dev.example .env
        echo "APP_KEY=base64:$(openssl rand -base64 32)" >> .env
        echo "DB_TEST_HOST=localhost" >> .env
        echo "DB_TEST_PORT=5432" >> .env

    - name: Install dependencies
      working-directory: ./backend
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run tests directly with PHPUnit
      working-directory: ./backend
      env:
        DB_TEST_HOST: localhost
        DB_TEST_PORT: 5432
      run: |
        php artisan key:generate
        sleep 5
        ./vendor/bin/phpunit